# Nombre del servicio y su NUEVO puerto
spring.application.name=internship-service
server.port=8081

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:internship_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Neo4j
spring.neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
spring.neo4j.authentication.username=${NEO4J_USER:neo4j}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:password123}

# Swagger UI / OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración de Elasticsearch
elasticsearch.url=${ELASTICSEARCH_URL:http://elasticsearch:9200}
elasticsearch.index=${ELASTICSEARCH_INDEX:pasantias-ofertas}