# Nombre del servicio y su NUEVO puerto
spring.application.name=internship-service
server.port=8081

# Configuración de Base de Datos SQLite
spring.datasource.url=jdbc:sqlite:internship.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true