sonar.projectKey=g7-internship-and-linkages-platform
sonar.projectName=Sistema Inteligente de Gestión de Pasantías y Vinculación con la Sociedad
sonar.sourceEncoding=UTF-8

sonar.sources=apps/auth-service/src/main/java,apps/document-service/src/main/java,apps/evaluation-service/src/main/java,apps/gateway-service/src/main/java,apps/hours-service/src/main/java,apps/internship-service/src/main/java,apps/linkage-service/src/main/java,apps/notification-service/src/main/java,apps/report-service/src/main/java

sonar.tests=apps/auth-service/src/test/java,apps/document-service/src/test/java,apps/evaluation-service/src/test/java,apps/gateway-service/src/test/java,apps/hours-service/src/test/java,apps/internship-service/src/test/java,apps/linkage-service/src/test/java,apps/notification-service/src/test/java,apps/report-service/src/test/java

sonar.java.source=21
sonar.java.binaries=apps/auth-service/target/classes,apps/document-service/target/classes,apps/evaluation-service/target/classes,apps/gateway-service/target/classes,apps/hours-service/target/classes,apps/internship-service/target/classes,apps/linkage-service/target/classes,apps/notification-service/target/classes,apps/report-service/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/build/**,apps/ai-service/**,apps/frontend-web/**,apps/mobile/**,apps/desktop/**
