spring.application.name=notification-service
server.port=8087

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notification_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Apache Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configuración de MQTT Broker (HiveMQ Cloud por defecto)
mqtt.broker.host=${MQTT_HOST:58567514d2724107bcd88d74e13a8bd8.s1.eu.hivemq.cloud}
mqtt.broker.port=${MQTT_PORT:8883}
mqtt.broker.username=${MQTT_USERNAME:mqttuser}
mqtt.broker.password=${MQTT_PASSWORD:Mqtt2026@}
mqtt.broker.client-id=${MQTT_CLIENT_ID:notification-service-client}

# Swagger UI / OpenAPI config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
