spring.application.name=linkage-service
server.port=8084

# Configuración de Base de Datos SQLite
spring.datasource.url=jdbc:sqlite:linkage.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas en la terminal (súper útil para debuggear)
spring.jpa.show-sql=true