name: GitOps - Infraestructura QA

on:
  push:
    branches:
      - QA # El robot se despierta si subes código a la rama QA

jobs:
  terraform:
    name: 'Desplegar Terraform en QA'
    runs-on: ubuntu-latest
    
    # Aquí el robot saca las llaves de su bolsillo secreto
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
    - name: 📥 Descargar código
      uses: actions/checkout@v3

    - name: 🛠️ Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: 🚀 Inicializar Terraform
      run: terraform init
      working-directory: ./infra/qa

    - name: 🏗️ Construir Infraestructura
      run: terraform apply -auto-approve
      working-directory: ./infra/qa